from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(summary, ai_story, forecast_text):

    filename = "DataSage_AI_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ---------------- TITLE ---------------- #

    story.append(
        Paragraph(
            "<b><font size=20>DataSage AI Report</font></b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- DATASET ---------------- #

    story.append(
        Paragraph(
            "<b>Dataset Overview</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(summary.replace("\n", "<br/>"), styles["BodyText"])
    )

    story.append(Spacer(1, 20))

    # ---------------- AI STORY ---------------- #

    story.append(
        Paragraph(
            "<b>AI Executive Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(ai_story.replace("\n", "<br/>"), styles["BodyText"])
    )

    story.append(Spacer(1, 20))

    # ---------------- FORECAST ---------------- #

    story.append(
        Paragraph(
            "<b>Forecast Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            forecast_text.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- FOOTER ---------------- #

    story.append(
        Paragraph(
            "Generated by DataSage AI",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename