
import re


from reportlab.platypus import Image
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


# =====================================================
# FORMAT AI STORY
# =====================================================

def format_ai_story(ai_story):

    lines = []

    icons = {
        "Executive Summary": "Executive Summary",
        "Key Findings": "Key Findings",
        "Business Recommendations": "Business Recommendations",
        "Risks": "Risks",
        "Next Steps": "Next Steps"
    }

    for line in ai_story.split("\n"):

        line = line.strip()

        if not line:
            continue

        # Remove markdown
        line = re.sub(r"^#+\s*", "", line)
        line = line.replace("**", "")

        if line in icons:

            lines.append(
                f"<br/><b>{icons[line]}</b><br/>"
            )

        else:

            lines.append(
                f"• {line}<br/>"
            )

    return "".join(lines)


# =====================================================
# GENERATE PDF
# =====================================================

def generate_pdf(summary, ai_story, forecast_text):

    filename = "DataSage_AI_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # =====================================================
    # TITLE
    # =====================================================

    story.append(
        Paragraph(
            "<font size='24'><b>Business Intelligence Report</b></font>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "<font size='14'>Generated by <b>DataSage AI</b></font>",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d %B %Y')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 25))

    # =====================================================
    # DATASET OVERVIEW
    # =====================================================

    story.append(
        Paragraph(
            "<b>1. Dataset Overview</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            summary.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

  
    # =====================================================
    # AI EXECUTIVE SUMMARY
    # =====================================================

    story.append(
        Paragraph(
            "<b>2. AI Executive Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            format_ai_story(ai_story),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # =====================================================
    # FORECAST ANALYSIS
    # =====================================================

    story.append(
        Paragraph(
            "<b>3. Forecast Analysis</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            forecast_text.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 25))

    # =====================================================
    # CONCLUSION
    # =====================================================

    story.append(
        Paragraph(
            "<b>4. Conclusion</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            "This report was automatically generated using DataSage AI. "
            "The insights presented are based on statistical analysis, "
            "machine learning, and AI-generated business recommendations "
            "to support informed decision-making.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # =====================================================
    # FOOTER
    # =====================================================

    story.append(
        Paragraph(
            "<i>© 2026 DataSage AI | AI-Powered Business Intelligence Platform</i>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename