import streamlit as st

from llm.storyteller import explain_forecast

from analysis.forecasting import (
    prepare_forecast_data,
    forecast_values,
    create_forecast_chart
)


def show_forecast(df, semantic_info):

    # =====================================================
    # HEADER
    # =====================================================

    st.header("🔮 Forecast Dashboard")

    st.caption(
        "Predict future trends using Machine Learning and receive "
        "AI-powered business explanations."
    )

    # =====================================================
    # PREPARE FORECAST DATA
    # =====================================================

    forecast_df, date_col, target = prepare_forecast_data(
        df,
        semantic_info
    )

    if forecast_df is None:

        st.warning(
            "Forecasting is not available for this dataset."
        )

        return

    st.success("✅ Forecast-ready dataset detected!")

    # =====================================================
    # FORECAST CONFIGURATION
    # =====================================================

    st.markdown("---")

    st.subheader("⚙️ Forecast Configuration")

    c1, c2 = st.columns(2)

    with c1:
        st.info(
            f"📅 **Date Column**\n\n{date_col}"
        )

    with c2:
        st.info(
            f"🎯 **Target KPI**\n\n{target}"
        )

    # =====================================================
    # FORECAST DATA PREVIEW
    # =====================================================

    st.markdown("---")

    st.subheader("📋 Forecast Dataset Preview")

    st.caption(
        "Preview of the processed dataset used for forecasting."
    )

    st.dataframe(
        forecast_df.head(),
        width="stretch"
    )

    # =====================================================
    # FORECAST SETTINGS
    # =====================================================

    st.markdown("---")

    st.subheader("📅 Forecast Settings")

    forecast_days = st.selectbox(
        "Forecast Period",
        [7, 30, 90],
        index=1
    )

    # =====================================================
    # GENERATE FORECAST
    # =====================================================

    if st.button("📈 Generate Forecast"):

        with st.spinner("Training forecasting model..."):

            forecast = forecast_values(
                forecast_df,
                date_col,
                target,
                forecast_days
            )

            chart = create_forecast_chart(
                forecast_df,
                forecast,
                date_col,
                target
            )

            # ---------------- KPI CALCULATIONS ---------------- #

            first_prediction = forecast["Prediction"].iloc[0]
            last_prediction = forecast["Prediction"].iloc[-1]

            growth = (
                (last_prediction - first_prediction)
                / first_prediction
            ) * 100

        st.success("✅ Forecast Generated Successfully!")

        # =====================================================
        # FORECAST SUMMARY
        # =====================================================

        st.markdown("---")

        st.subheader("📊 Forecast Summary")

        c1, c2, c3 = st.columns(3)

        with c1:
            st.metric(
                "📅 Forecast Period",
                f"{forecast_days} Days"
            )

        with c2:
            st.metric(
                "📈 Predicted Growth",
                f"{growth:.2f}%"
            )

        with c3:
            st.metric(
                "🎯 Target KPI",
                target
            )

        st.info(
    """
🤖 **Forecast Model**

This forecast is generated using a **Random Forest Regression** model trained on the historical dataset.

The model analyzes historical patterns to estimate future values and provides an AI-generated business interpretation of the forecast.
"""
)
        # =====================================================
        # FORECAST CHART
        # =====================================================

        st.markdown("---")

        st.subheader("📈 Forecast Visualization")

        st.plotly_chart(
            chart,
            width="stretch"
        )

        # =====================================================
        # FORECAST TABLE
        # =====================================================

        st.markdown("---")

        st.subheader("📋 Forecast Results")

        st.caption(
            "Predicted values generated by the forecasting model."
        )

        st.dataframe(
            forecast,
            width="stretch"
        )

        # =====================================================
        # AI FORECAST EXPLANATION
        # =====================================================

        st.markdown("---")

        st.subheader("🤖 AI Forecast Explanation")

        st.info(
            "AI interprets the forecast and provides business-focused recommendations."
        )

        with st.spinner("Generating AI explanation..."):

            explanation = explain_forecast(
                target,
                growth,
                forecast_days
            )

            st.session_state["forecast_explanation"] = explanation

        st.markdown(explanation)